project:
  type: website
  output-dir: docs

website:
  title: "🜏 Apprentice Codex 🜏"
  navbar:
    left:
      - href: index.qmd
        text: Codex
      - text: The Path
        menu:
          - href: trials/index.qmd
            text: Overview
          - href: trials/ladder.qmd
            text: The Ladder
          - href: trials/bestiary.qmd
            text: The Bestiary
          - href: trials/sigils.qmd
            text: Minor Mysteries
      - text: Forbidden Library
        menu:
          - href: library/python-good-practices.qmd
            text: Python Good Practices
          - href: library/fermiml.qmd
            text: FermiML
          - href: library/tensor-networks.qmd
            text: Tensor Networks
          - href: library/qec.qmd
            text: Quantum Error Correction
          - href: library/quantum-simulation.qmd
            text: Quantum Simulation

format:
  html:
    theme: darkly
    css: styles.css
    toc: true