name: Deploy Quarto Site

on:
  push:
    branches: [main]

  pull_request:
    branches: ["*"]

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  issues: write
  discussions: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Deploy to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy
        uses: actions/deploy-pages@v4